config/routes.rb
GameBlog::Application.routes.draw do
  resources :skins,:only=>[:index,:show] do
    put :select_skin, :on=>:member
  end

  resources :blog_profiles

  resources :blog, :only=>[:index,:show] do
    resources :comments, :only =>[:new, :create]
  end
  match 'blog/:id/:entry_id/' => 'blog#show', :as => :blog_show
  match 'blog/:id/' => 'blog#index', :as => :blog_index
  resources :blog_setting, :only=>[:edit,:show,:update] do
    
  end

  resources :entries ,:only =>[:index,:new,:create,:show,:update,:edit,:destroy] do
    resources :comments, :only =>[:new, :create]
  end

  devise_for :bloggers

  root :to => "entries#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
   belongs_to :blogger
   has_many :comments
   scope :latest ,order('updated_at desc')
   scope :public_entries ,where('public_flag=1')
   validates :title,:sentence,:presence =>true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.xml
  def index
    @blogger = current_blogger
    @entries = Entry.where("blogger_id=?",@blogger.id).latest
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.xml
  def show
    @blogger = current_blogger
    @entry = Entry.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.xml
  def new
    @blogger = current_blogger
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @blogger = current_blogger
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.xml
  def create
    @entry = Entry.new(params[:entry])
    @blogger = current_blogger
    @entry.blogger_id = @blogger.id
    respond_to do |format|
      if @entry.save
        format.html { redirect_to(@entry, :notice => 'Entry was successfully created.') }
        format.xml  { render :xml => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.xml
  def update
    @blogger = current_blogger
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to(@entry, :notice => 'Entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.xml
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to(entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def is_public(flag)
    if flag==1
      return "PUBLIC"
    else
      return "NOT PUBLIC"
    end
  end

  def format_string_length(message, max_length)
    if (message.length > max_length)
      return CGI.escapeHTML(message[0,max_length]+".....")
    else
      return CGI.escapeHTML(message)
    end
  end
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title ,'タイトル' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sentence ,'本文'%><br />
    <%= f.text_area :sentence %>
  </div>
  <div class="field">
    <%= f.label :public_flag ,'公開する'%><br />
    <%= f.check_box :public_flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="entry_form">
<h2>記事編集</h2>

<%= render 'form' %>

<%= link_to '詳細', @entry %> |
<%= link_to '一覧へ', entries_path %>
</div>

app/views/entries/index.html.erb
<article>
      <h2>記事一覧</h2>

      <table class="section">
        <tr >
          <th class="list_menu">タイトル</th>
          <th class="list_menu">記事</th>
          <th class="list_menu">公開/非公開</th>
          <th class="list_menu">投稿日付</th>
          <th class="list_menu"></th>
          <th class="list_menu"></th>
          <th class="list_menu"></th>
        </tr>

      <% @entries.each do |entry| %>
        <tr >
          <td class="entry"><%= entry.title %></td>
          <td class="entry"><%= format_string_length(entry.sentence,20) %></td>
          <td class="entry"><%= is_public(entry.public_flag) %></td>
          <td class="datetime"><%= entry.created_at.strftime("%Y/%m/%d") %></td>
          <td ><%= link_to '詳細', entry %></td>
          <td><%= link_to '編集', edit_entry_path(entry) %></td>
          <td><%= link_to '削除', entry, :confirm => '削除してもいいですか?', :method => :delete %></td>
        </tr>
      <% end %>
      </table>
</article>

app/views/entries/new.html.erb
<div class="entry_form">
<h2>記事投稿</h2>

<%= render 'form' %>
<%= link_to '一覧へ', entries_path %>
</div>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="entry_form">
<p><%= link_to '編集', edit_entry_path(@entry) %></p>
<p>
  <b>タイトル:</b>
  <%= @entry.title %>
</p>
<p>
  <b>本文:</b>
  <%= @entry.sentence %>
</p>
<p>
  <b>公開・非公開:</b>
  <%= is_public(@entry.public_flag) %>
</p>
</div>