config/routes.rb
GameBlog::Application.routes.draw do
  resources :skins,:only=>[:index,:show] do
    put :select_skin, :on=>:member
  end

  resources :blog_profiles

  resources :blog, :only=>[:index,:show] do
    resources :comments, :only =>[:new, :create]
  end
  match 'blog/:id/:entry_id/' => 'blog#show', :as => :blog_show
  match 'blog/:id/' => 'blog#index', :as => :blog_index
  resources :blog_setting, :only=>[:edit,:show,:update] do
    
  end

  resources :entries ,:only =>[:index,:new,:create,:show,:update,:edit,:destroy] do
    resources :comments, :only =>[:new, :create]
  end

  devise_for :bloggers

  root :to => "entries#index"

end

app/models/blog_profile.rb
class BlogProfile < ActiveRecord::Base
   validates :name,:presence =>true
   validates :skin_id,:presence =>true,:numericality=>true
end

app/controllers/blog_profiles_controller.rb
class BlogProfilesController < ApplicationController
  # GET /blog_profiles
  # GET /blog_profiles.xml
  def index
    @blog_profiles = BlogProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blog_profiles }
    end
  end

  # GET /blog_profiles/1
  # GET /blog_profiles/1.xml
  def show
    begin
      @blogger = current_blogger
      @blog_profile = BlogProfile.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @blog_profile }
      end
    rescue  ActiveRecord::RecordNotFound =>e
      @blog_profile = BlogProfile.new
      respond_to do |format|
        format.html { render :action => "new" }
        end
      end
   
  end

  # GET /blog_profiles/new
  # GET /blog_profiles/new.xml
  def new
    @blog_profile = BlogProfile.new
    @blogger = current_blogger
    @blog_profile.blogger_id = @blogger.id
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog_profile }
    end
  end

  # GET /blog_profiles/1/edit
  def edit
    @blogger = current_blogger
    @blog_profile = BlogProfile.find(params[:id])
  end

  # POST /blog_profiles
  # POST /blog_profiles.xml
  def create
    @blog_profile = BlogProfile.new(params[:blog_profile])
    respond_to do |format|
      if @blog_profile.save
        format.html { redirect_to(@blog_profile, :notice => 'Blog profile was successfully created.') }
        format.xml  { render :xml => @blog_profile, :status => :created, :location => @blog_profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_profiles/1
  # PUT /blog_profiles/1.xml
  def update
    @blog_profile = BlogProfile.find(params[:id])

    respond_to do |format|
      if @blog_profile.update_attributes(params[:blog_profile])
        format.html { redirect_to(@blog_profile, :notice => 'Blog profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_profiles/1
  # DELETE /blog_profiles/1.xml
  def destroy
    @blog_profile = BlogProfile.find(params[:id])
    @blog_profile.destroy

    respond_to do |format|
      format.html { redirect_to(blog_profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/blog_profiles_helper.rb
module BlogProfilesHelper
end

app/views/blog_profiles/_form.html.erb
<%= form_for(@blog_profile) do |f| %>
  <% if @blog_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_profile.errors.count, "error") %> prohibited this blog_profile from being saved:</h2>

      <ul>
      <% @blog_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :blog_name %><br />
    <%= f.text_field :blog_name %>
  </div>
  <div class="field">
    <%= f.label :skin_id %><br />
    <%= f.text_field :skin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_profiles/edit.html.erb
<h1>Editing blog_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_profile %> |
<%= link_to 'Back', blog_profiles_path %>

app/views/blog_profiles/index.html.erb
<h1>Listing blog_profiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Blog name</th>
    <th>Skin</th>
    <th>Blogger</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_profiles.each do |blog_profile| %>
  <tr>
    <td><%= blog_profile.name %></td>
    <td><%= blog_profile.blog_name %></td>
    <td><%= blog_profile.skin_id %></td>
    <td><%= blog_profile.blogger_id %></td>
    <td><%= link_to 'Show', blog_profile %></td>
    <td><%= link_to 'Edit', edit_blog_profile_path(blog_profile) %></td>
    <td><%= link_to 'Destroy', blog_profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog profile', new_blog_profile_path %>

app/views/blog_profiles/new.html.erb
<h1>New blog_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_profiles_path %>

app/views/blog_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blog_profile.name %>
</p>

<p>
  <b>Blog name:</b>
  <%= @blog_profile.blog_name %>
</p>

<p>
  <b>Skin:</b>
  <%= @blog_profile.skin_id %>
</p>

<p>
  <b>Blogger:</b>
  <%= @blog_profile.blogger_id %>
</p>


<%= link_to 'Edit', edit_blog_profile_path(@blog_profile) %> |