config/routes.rb
GameBlog::Application.routes.draw do
  resources :skins,:only=>[:index,:show] do
    put :select_skin, :on=>:member
  end

  resources :blog_profiles

  resources :blog, :only=>[:index,:show] do
    resources :comments, :only =>[:new, :create]
  end
  match 'blog/:id/:entry_id/' => 'blog#show', :as => :blog_show
  match 'blog/:id/' => 'blog#index', :as => :blog_index
  resources :blog_setting, :only=>[:edit,:show,:update] do
    
  end

  resources :entries ,:only =>[:index,:new,:create,:show,:update,:edit,:destroy] do
    resources :comments, :only =>[:new, :create]
  end

  devise_for :bloggers

  root :to => "entries#index"

end

app/models/skin.rb
class Skin < ActiveRecord::Base
end

app/controllers/skins_controller.rb
class SkinsController < ApplicationController
  # GET /skins
  # GET /skins.xml
  def index
    @blogger = current_blogger
    @skins = Skin.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @skins }
    end
  end

  # GET /skins/1
  # GET /skins/1.xml
  def show
    @blogger = current_blogger
    @skin = Skin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @skin }
    end
  end

  # DELETE /skins/1
  # DELETE /skins/1.xml
  def destroy
    @skin = Skin.find(params[:id])
    @skin.destroy

    respond_to do |format|
      format.html { redirect_to(skins_url) }
      format.xml  { head :ok }
    end
  end

  def select_skin
    @blogger = current_blogger
    @skin = Skin.find(params[:id])
    @profile = BlogProfile.find(:first,:conditions=>["blogger_id=?",@blogger.id])
    @profile.update_attribute(:skin_id, @skin.id)
    render :update  do  |page|
      page.insert_html :top, 'selected_skin', :partial=>'selected_skin'
    end
  end

end

app/helpers/skins_helper.rb
module SkinsHelper
end

app/views/skins/_selected_skin.html.erb
現在選択中のスキン
<div id="skin_info">
<b>Title:</b>  <%= @skin.title %>
</div>

app/views/skins/index.html.erb
<h1>スキン一覧</h1>
<table>
  <tr>
    <th>スキンタイトル</th>
    <th></th>
    <th></th>
  </tr>
<% @skins.each do |skin| %>
  <tr>
    <td><%= skin.title %></td>
    <td><%= link_to 'Show', skin %></td>
    <td><%= link_to 'Destroy', skin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/skins/show.html.erb
<div id="selected_skin"></div>

<p>
  <b>Title:</b>
  <%= @skin.title %>
</p>

<%= link_to 'このスキンを選択',[:select_skin, @skin],:confirm => '本当に？',:remote=>true,:method=>:put %>|
<%= link_to '一覧へ', skins_path %>