config/routes.rb
GameBlog::Application.routes.draw do
  resources :skins,:only=>[:index,:show] do
    put :select_skin, :on=>:member
  end

  resources :blog_profiles

  resources :blog, :only=>[:index,:show] do
    resources :comments, :only =>[:new, :create]
  end
  match 'blog/:id/:entry_id/' => 'blog#show', :as => :blog_show
  match 'blog/:id/' => 'blog#index', :as => :blog_index
  resources :blog_setting, :only=>[:edit,:show,:update] do
    
  end

  resources :entries ,:only =>[:index,:new,:create,:show,:update,:edit,:destroy] do
    resources :comments, :only =>[:new, :create]
  end

  devise_for :bloggers

  root :to => "entries#index"

end

app/views/common/_blogger_info.html.erb
 <%= link_to 'プロフィール情報',  :controller =>'blog_profiles', :action => 'show',:id=>@blogger.id %>

app/views/common/_footer.html.erb
<div id="footer">game_blog 2010-12-20(<%=t :site_title%>)</div>

app/views/common/_header.html.erb
<header>
<%=image_tag("GAME_BLOG.aspx.jpg",:border => 0)%>
</header>

app/views/common/_menu.html.erb
<% if @blogger != nil  %>
 <div >
  <div class="login_user_info" >
    <%=@blogger.handle_name %>さん。こんばんは！&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'ブログをみる',  :controller =>'blog', :action => 'index',:id=>@blogger.id %>&nbsp;&nbsp;|&nbsp;&nbsp;
  </div>
 </div>
<table>
  <tr><td class="menu_text">
    <%= link_to '記事一欄へ',  :controller =>'entries', :action => 'index' %> &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to '新規投稿', new_entry_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'スキン選択', :controller =>'skins' ,:action=>'index' %>&nbsp;&nbsp;|&nbsp;&nbsp;
  </td></tr>
</table>
<hr>
<% end %>